[pytest]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"
markers = [
    "integration"
]

env = [
    "DEFAULT_FLOW_RETRIES=0",
    "DEFAULT_FLOW_RETRY_DELAY_SECONDS=0",
]
